name = "servicetop"
main = "src/worker.ts"
compatibility_date = "2023-05-26"
node_compat = true

# # KV Namespace binding - For more information: https://developers.cloudflare.com/workers/runtime-apis/kv
[[kv_namespaces]]
binding = "state"
# preview_id = "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"
# id = "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"
preview_id = "2ab5d88ae4b9402da70762724aa89089"
id = "18750542e083458e89dfdc9494fce35c"

# # Durable Object binding - For more information: https://developers.cloudflare.com/workers/runtime-apis/durable-objects
# [[durable_objects]]
# binding = "MY_DURABLE_OBJECT"
# class_name = "MyDurableObject"

# # Bucket binding - For more information: https://developers.cloudflare.com/workers/runtime-apis/kv#bucket
# [[buckets]]
# binding = "MY_BUCKET"
# name = "my-bucket"
# bucket_id = "yyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyy"

# # Service binding - For more information: https://developers.cloudflare.com/workers/platform/services
# [[routes]]
# binding = "MY_SERVICE"
# pattern = "/api/*"
# script = "api.js"

# # Queue binding - For more information: https://developers.cloudflare.com/workers/runtime-apis/queues
# [[queues]]
# binding = "MY_QUEUE"
# name = "my-queue"
# zone_id = "zzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzz"

[vars]
AWS_ECS_CLUSTER_NAME = "cuckoo"
AWS_ECS_EXECUTION_ROLE_ARN = "arn:aws:iam::455649480398:role/CuckooClusterTaskRole"
AWS_ELB_LISTENER_ARN = "arn:aws:elasticloadbalancing:us-east-2:455649480398:listener/app/cuckoo/e9063e45bb68a96d/855f1905b9c3836e"
AWS_ELB_SECURITY_GROUP_ID	= "sg-017228e39a0ee2e52"
AWS_ELB_VPC_ID = "vpc-0e76c879279b3c143"
AWS_REGION = "us-east-2"
CF_EMAIL = "admin@resolute.work"
CF_TARGET = "cuckoo-2099159911.us-east-2.elb.amazonaws.com"
CF_ZONE_ID = "e85c93b8ac83aef2bd07f5d147b7e802"
OXYLABS_USER = "cuckoo"
PARENT_DOMAIN	= "cuckoo.resolute.work"
PARENT_DOMAIN2 = "cuckoo.phantasm.group"
WORKER_AUTH_KEY = "x-cuckoo-auth"
# MY_VARIABLE = "production_value"

# Needed secrets:
# - AWS_ACCESS_ID
# - AWS_ACCESS_SECRET
# - AWS_ELB_VPC_ID
# - AWS_ELB_LISTENER_ARN
# - AWS_ELB_TOKEN
# - AWS_ELB_SECURITY_GROUP
# - AWS_REGION
# - AWS_ECS_EXECUTION_ROLE_ARN
# - AWS_ECS_CLUSTER_NAME
# - CF_TARGET
# - CF_TOKEN
# - CF_KEY
# - CF_EMAIL
# - CF_ZONE_ID
# - WORKER_AUTH_KEY
# - WORKER_AUTH_VALUE
# - PARENT_DOMAIN

# [env.staging]
# MY_VARIABLE = "staging_value"

# [env.shared]
# SHARED_VARIABLE = "shared_value"
